apiVersion: v1
kind: Pod
metadata: 
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers: 
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo the app is running && sleep 3600']
    env:
    - name: FIRSTNAME
      value: "Teddy"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    args: ['sh', '-c', 'until nslookup myservice.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done']
