apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis  # Adjusted label key to be more conventional
spec:
  containers:
  - name: redis
    image: redis
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 6379  # Updated to the standard Redis port
      protocol: TCP
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: Exists  # No need to specify values for 'Exists' operator
