apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myapp
  template: 
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.1-alpine
          ports: 
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"